src/Entity/Employer.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EmployerRepository")
 */
class Employer
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $matricule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomcomplet;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naiss;

    /**
     * @ORM\Column(type="float")
     */
    private $salaire;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Service", inversedBy="employers")
     */
    private $id_service;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getNomcomplet(): ?string
    {
        return $this->nomcomplet;
    }

    public function setNomcomplet(string $nomcomplet): self
    {
        $this->nomcomplet = $nomcomplet;

        return $this;
    }

    public function getDateNaiss(): ?\DateTimeInterface
    {
        return $this->date_naiss;
    }

    public function setDateNaiss(\DateTimeInterface $date_naiss): self
    {
        $this->date_naiss = $date_naiss;

        return $this;
    }

    public function getSalaire(): ?float
    {
        return $this->salaire;
    }

    public function setSalaire(float $salaire): self
    {
        $this->salaire = $salaire;

        return $this;
    }

    public function getIdService(): ?service
    {
        return $this->id_service;
    }

    public function setIdService(?service $id_service): self
    {
        $this->id_service = $id_service;

        return $this;
    }
}

src/Entity/Service.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ServiceRepository")
 */
class Service
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $libelle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Employer", mappedBy="id_service")
     */
    private $employers;

    public function __construct()
    {
        $this->employers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * @return Collection|Employer[]
     */
    public function getEmployers(): Collection
    {
        return $this->employers;
    }

    public function addEmployer(Employer $employer): self
    {
        if (!$this->employers->contains($employer)) {
            $this->employers[] = $employer;
            $employer->setIdService($this);
        }

        return $this;
    }

    public function removeEmployer(Employer $employer): self
    {
        if ($this->employers->contains($employer)) {
            $this->employers->removeElement($employer);
            // set the owning side to null (unless already changed)
            if ($employer->getIdService() === $this) {
                $employer->setIdService(null);
            }
        }

        return $this;
    }
}

src/Controller/EmployerController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use App\Repository\ServiceRepository;
use App\Repository\EmployerRepository;
use Symfony\Component\Form\Extension\Core\Type\DateType;

use App\Entity\Employer;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Service;

class EmployerController extends AbstractController
{
    /**
     * @Route("/employer", name="employer")
     * 
     */
    public function list()
    {
$repo = $this->getDoctrine()->getRepository(Employer::class);
$employers = $repo->findAll();

        return $this->render('employer/index.html.twig', [
            'controller_name' => 'EmployerController',
             'employers' => $employers 
        ]);
    }
/**
 * @Route("/",name="home")
 */

    public function home(){
        return $this->render('employer/home.html.twig');
    }
 /**
  * @Route("/employer/new",name="employer_form")
  * @Route("/employer/{id}edit",name="edit")
  */
    public function froms(Employer $employer = null,Request $request,ObjectManager $manager){
   if(!$employer){
    $employer= new Employer();
   }
      

$form=$this->createFormBuilder($employer)
            ->add('matricule')
            ->add('nomcomplet')
            ->add('date_naiss', DateType::class, [
                'widget'=>'single_text',
                'format'=>'yyyy-MM-dd'
            ])
            ->add('salaire')
            ->add('id_service', EntityType::class, [
                'class'=> Service::class, 'choice_label'=>'libelle'
            ])

             ->getForm();

$form->handleRequest($request);

if($form->isSubmitted() && $form->isValid()){
   $manager->persist($employer);
   $manager->flush();
   return $this->redirectToRoute('employer');
  
}
        return $this->render('employer/form.html.twig',[
         'formemp' => $form->createView(),
         'editMode'=>$employer->getId() !== null
        ]);
    }
    /**
     *  @Route("/employer/{id}delate",name="delt")
     */
public function delete(Employer $employer,ObjectManager $manager){
  
$manager->remove($employer);
$manager->flush();
 $this->addFlash('danger','employer supprimé avec succés');

return $this->redirectToRoute('employer',['employer'=>$employer]);

}
/**
 * @Route("/employer/serv",name="service_form")
 * @Route("/employer/{id}editsev",name="editserv")

 */
public function formser(Service $service = null,Request $request,ObjectManager $manager){
    if(!$service){
        $service= new Service();
       }
          
    $form=$this->createFormBuilder($service)
                ->add('libelle')
                
                 ->getForm();
    
    $form->handleRequest($request);
    
    if($form->isSubmitted() && $form->isValid()){
       $manager->persist($service);
       $manager->flush();
//    return $this->redirectToRoute('employer);
      
    }
    $repo = $this->getDoctrine()->getRepository(Service::class);
    $services = $repo->findAll();
            return $this->render('employer/service.html.twig',[
             'formserv' => $form->createView(),
             'services' => $services ,
              'editMode'=>$service->getId() !== null
            ]);

        }
     /**
     *  @Route("/employer/{id}delatesev",name="deltsev")
     */
public function deletesev(Service $service,ObjectManager $manager){
  
    $manager->remove($service);
    $manager->flush();
     $this->addFlash('danger','service supprimé avec succés');
    
    return $this->redirectToRoute('employer',['service'=>$service]);
    
    }


}

templates/base.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>

    <link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">
    {% block stylesheets %}{% endblock %}

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{path('home')}}">MySymfony</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
            aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
            <a class="nav-link active"  href="{{path('employer')}}">listeEmployer<span class="sr-only">(current)</span></a>
             </li>
             <li class="nav-item">
             <a class="nav-link" href="{{path('employer_form')}}">AjouterEmployer</a>
             </li>
           <li class="nav-item">
             <a class="nav-link" href="/employer/serv">Ajouter Service</a>
             </li>
    </ul>
            
        </div>
    </nav>

<div class="container">
        {% block body %}{% endblock %}

</div>

    {% block javascripts %}{% endblock %}
</body>

</html>

templates/employer/form.html.twig
{% extends 'base.html.twig' %}

{% form_theme formemp 'bootstrap_4_layout.html.twig' %}
{% block body %}
<h1>création d'employer </h1>
{{ form_start(formemp) }}

{{ form_row(formemp.matricule) }}
{{ form_row(formemp.nomcomplet)  }}
{{ form_row(formemp.date_naiss)  }}
{{ form_row(formemp.salaire ) }}
{{ form_row(formemp.id_service) }}

<button type="submit" class="btn-success">
{% if editMode %}
 Enregister Modification
{% else %}
Ajouter un employer
 {% endif %} 
</button>


{{ form_end(formemp) }}


{{form(formemp)}}



{% endblock %}

templates/employer/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}

<h1>Bienvenue !!!!!</h1>

{% endblock %}

templates/employer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello EmployerController!{% endblock %}

{% block body %}
<br>
{% for message in app.flashes('danger') %}
<div class="alert alert-danger">
{{message}}sss
</div>
{% endfor %}

{# <style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Salut {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/dijaseck/Bureau/projetsymfony/projet1/src/Controller/EmployerController.php'|file_link(0) }}">src/Controller/EmployerController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/dijaseck/Bureau/projetsymfony/projet1/templates/employer/index.html.twig'|file_link(0) }}">templates/employer/index.html.twig</a></code></li>
    </ul>
</div> #}
 <center><h1> La liste des employers</h1> </center>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Matricule</th>
      <th scope="col">Nomcomplet</th>
      <th scope="col">Date_naiss</th>
      <th scope="col">Salaire</th>
      <th scope="col">id_service</th>
      <th scope="col">Modifier</th>
      <th scope="col">Supprimer</th>
    </tr>
    </thead>
    <tbody>
{% for employer in employers %}
  
   <tr>
   <td>{{employer.matricule}}</td>
      <td>{{employer.nomcomplet}}</td>
      <td>{{employer.dateNaiss | date('d/m/y')}}</td>
    <td>{{employer.salaire}} FCF</td>
    <td>{{employer.idService.libelle}}</td>
     <td>
     <button class="btn btn-primary btn-lg">
     <a href="{{path('edit',{id:employer.id})}}">Modifier</a>
     </td>
     <td>
     <button class="btn btn-danger btn-lg">
     <a href="{{path('delt',{id:employer.id})}}">Supprimer</a>
     </td>
    </tr>
{% endfor %}
  </tbody>
</table>
{% endblock %}

templates/employer/service.html.twig
{% extends 'base.html.twig' %}

{% form_theme formserv 'bootstrap_4_layout.html.twig' %}
{% block body %}
<br>
{% for message in app.flashes('danger') %}
<div class="alert alert-danger">
{{message}}
</div>
{% endfor %}
<h1>création d'un service </h1>
{{ form_start(formserv) }}

{{ form_row(formserv.libelle) }}
<button type="submit" class="btn-success">
{% if editMode %}
 Enregister Modification
 {% else %}
Ajouter une service
 {% endif %} 
</button>
{{ form_end(formserv) }}
{{form(formserv)}}
{# liste des service #}

<center><h1> La liste des services</h1> </center>
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">libelle</th>
      <th scope="col">Modifier</th>
      <th scope="col">Supprimer</th>
    </tr>
    </thead>
    <tbody>
{% for service in services %}
  
   <tr>
   <td>{{service.id}}</td>
      <td>{{service.libelle}}</td>
    
     <td>
     <button class="btn btn-primary btn-lg">
     <a href="{{path('editserv',{id:service.id})}}">Modifier</a>
     </td>
     <td>
     <button class="btn btn-danger btn-lg">
     <a href="{{path('deltsev',{id:service.id})}}">Supprimer</a>
     </td>
    </tr>
{% endfor %}
  </tbody>
</table>



{% endblock %}